#!/bin/sh
[ -$# = 0 ] && {
	echo usage: gifinate '*.xpm'
	echo Convert XPM files to GIF files
}
[ -x /usr/bin/ppmtogif ] || {
        echo You need to install the NETPBM package.  This script needs the
        echo xpmtoppm and ppmtogif commands.
        exit
}
alpha=/tmp/alpha$$
for xpm
do
	case "$xpm" in
	  *.xpm)
		gif=`basename $xpm .xpm`.gif
		xpmtoppm --alphaout=$alpha $xpm | ppmtogif --alpha=$alpha >$gif
		;;
	  *)
		echo "gifinate: can't convert $xpm -- not a *.xpm file"
		;;
	esac
done
rm $alpha
